//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiveCore
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LIVECOREEntities : DbContext
    {
        public LIVECOREEntities()
            : base("name=LIVECOREEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<STATUS> STATUS { get; set; }
        public virtual DbSet<TIPOCONTRATO> TIPOCONTRATO { get; set; }
        public virtual DbSet<UNIDADE> UNIDADE { get; set; }
        public virtual DbSet<SERVICO> SERVICOes { get; set; }
        public virtual DbSet<AREAESCOPO> AREAESCOPO { get; set; }
        public virtual DbSet<EQUIPAMENTO> EQUIPAMENTOes { get; set; }
        public virtual DbSet<USUARIO> USUARIOs { get; set; }
    }
}
